# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('fname', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=40)),
                ('uname', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=1)),
                ('street', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
                ('zipcode', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=15)),
                ('profession', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
