# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 01:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourite_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=40)),
                ('product_desc', models.CharField(max_length=150)),
                ('product_age', models.PositiveIntegerField()),
                ('post_status', models.CharField(choices=[('A', 'A'), ('P', 'P')], default='A', max_length=1)),
                ('post_timestamp', models.DateTimeField(auto_now=True)),
                ('estimated_price', models.DecimalField(decimal_places=3, default=0.0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='PostReviews',
            fields=[
                ('comment', models.CharField(max_length=150)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('post_review_timestamp', models.DateTimeField(auto_now=True, primary_key=True, serialize=False)),
                ('pid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BarterSystem.Post')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Swap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swap_status', models.CharField(choices=[('A', 'A'), ('R', 'R'), ('P', 'P')], default='P', max_length=1)),
                ('swap_timestamp', models.DateTimeField(auto_now=True)),
                ('receiver_pid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_pid', to='BarterSystem.Post')),
                ('sender_pid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_pid', to='BarterSystem.Post')),
            ],
        ),
        migrations.CreateModel(
            name='SwapChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BarterSystem.ProductCategory')),
                ('pid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BarterSystem.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('pid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BarterSystem.Post')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('fname', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=40)),
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('age', models.PositiveIntegerField(default=16)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], default='M', max_length=1)),
                ('street', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
                ('zipcode', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=15)),
                ('profession', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserReviews',
            fields=[
                ('comment', models.CharField(max_length=150)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('user_review_timestamp', models.DateTimeField(auto_now=True, primary_key=True, serialize=False)),
                ('comment_on_uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_on_uid', to='BarterSystem.User')),
                ('commenting_uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commenting_uid', to='BarterSystem.User')),
            ],
        ),
        migrations.AddField(
            model_name='postreviews',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BarterSystem.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BarterSystem.ProductCategory'),
        ),
        migrations.AddField(
            model_name='post',
            name='posted_by_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_by_uid', to='BarterSystem.User'),
        ),
        migrations.AddField(
            model_name='like',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BarterSystem.Post'),
        ),
        migrations.AddField(
            model_name='like',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BarterSystem.User'),
        ),
        migrations.AddField(
            model_name='favourite',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BarterSystem.Post'),
        ),
        migrations.AddField(
            model_name='favourite',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BarterSystem.User'),
        ),
    ]
