# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 05:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BarterSystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swapchoice',
            old_name='cid',
            new_name='cid_id',
        ),
        migrations.RenameField(
            model_name='swapchoice',
            old_name='pid',
            new_name='pid_id',
        ),
    ]
